# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vteDwsJXagR1H4TEweLdGQdN3KSy9Tws
"""

import torch
#c=torch.device("cuda")
x = torch.rand(100001,10000)
w = torch.rand(10000, 50, requires_grad=True)

y=x@w
l = y.sum()
print(l)
l.backward()
w=w-w.grad*0.0001
l=(x@w).sum()